language: r
cache: packages
sudo: false
warnings_are_errors: false
git:
  depth: false
install:
  - Rscript install-packages.R
  
script:
  - Rscript update-data.R
  - Rscript testthat.R
  
after_success:

